import Link from "next/link";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { listCmsProjects } from "@/lib/server/business";
import { insertRow, updateRow, deleteRow, uploadPublicAsset } from "@/lib/server/supabase";

function slugify(value:string){return value.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'').slice(0,90)}
export default async function CmsProjectsPage(){ const items=await listCmsProjects(true);
async function create(formData:FormData){'use server'; const title=String(formData.get('title')||'').trim().slice(0,120); if(!title)return; const slug=slugify(String(formData.get('slug')||title)); const imageFile=formData.get('image_file');const uploaded=imageFile instanceof File&&imageFile.size?await uploadPublicAsset(imageFile,`projects/${slug}`):'';const row=await insertRow<any>('cms_projects',{title,title_en:String(formData.get('title_en')||'').slice(0,120)||null,slug,eyebrow:String(formData.get('eyebrow')||'').slice(0,120)||null,eyebrow_en:String(formData.get('eyebrow_en')||'').slice(0,120)||null,category:String(formData.get('category')||'').slice(0,120)||null,category_en:String(formData.get('category_en')||'').slice(0,120)||null,description:String(formData.get('description')||'').slice(0,1200),description_en:String(formData.get('description_en')||'').slice(0,1200)||null,long_description:String(formData.get('long_description')||'').slice(0,8000)||null,long_description_en:String(formData.get('long_description_en')||'').slice(0,8000)||null,tags:String(formData.get('tags')||'').split(',').map(v=>v.trim()).filter(Boolean).slice(0,20),image_url:uploaded||String(formData.get('image_url')||'').slice(0,1000)||null,demo_url:String(formData.get('demo_url')||'').slice(0,1000)||null,published:false,sort_order:100}); redirect(`/admin/projetos/${row.id}`)}
async function toggle(formData:FormData){'use server'; const id=String(formData.get('id')); const published=String(formData.get('published'))==='true'; await updateRow('cms_projects',id,{published:!published,updated_at:new Date().toISOString()}); revalidatePath('/admin/projetos'); revalidatePath('/projetos')}
async function remove(formData:FormData){'use server'; await deleteRow('cms_projects',String(formData.get('id'))); revalidatePath('/admin/projetos'); revalidatePath('/projetos')}
return <main className="admin-page"><div className="admin-page-heading"><div><span>CMS</span><h1>Projetos</h1></div><strong>{items.length}</strong></div><section className="admin-panel"><h2>Novo projeto</h2><form className="admin-form admin-form-grid" action={create}><label>Título PT<input name="title" required maxLength={120}/></label><label>Título EN<input name="title_en" maxLength={120}/></label><label>Slug<input name="slug" placeholder="gerado automaticamente"/></label><label>Eyebrow PT<input name="eyebrow" placeholder="SaaS • Gestão"/></label><label>Eyebrow EN<input name="eyebrow_en" placeholder="SaaS • Management"/></label><label>Categoria PT<input name="category" placeholder="Produto digital"/></label><label>Categoria EN<input name="category_en" placeholder="Digital product"/></label><label className="admin-span-2">Descrição PT<textarea name="description" required rows={3}/></label><label className="admin-span-2">Descrição EN<textarea name="description_en" rows={3}/></label><label className="admin-span-2">Descrição longa PT<textarea name="long_description" rows={5}/></label><label className="admin-span-2">Descrição longa EN<textarea name="long_description_en" rows={5}/></label><label>Tags<input name="tags" placeholder="SaaS, Dashboard, Gestão"/></label><label>Upload da capa<input name="image_file" type="file" accept="image/png,image/jpeg,image/webp,image/avif"/></label><label>ou Imagem HTTPS<input name="image_url" type="url" placeholder="https://..."/></label><label className="admin-span-2">Demo HTTPS<input name="demo_url" type="url" placeholder="https://..."/></label><button className="button button-primary admin-span-2">Criar rascunho</button></form></section><div className="admin-card-list">{items.map(item=><div className="admin-list-card static" key={item.id}><div><strong>{item.title}</strong><span>/{item.slug} · {item.category||'Sem categoria'}</span></div><div className="admin-inline-actions"><Link href={`/admin/projetos/${item.id}`}>Editar</Link><form action={toggle}><input type="hidden" name="id" value={item.id}/><input type="hidden" name="published" value={String(item.published)}/><button>{item.published?'Despublicar':'Publicar'}</button></form><form action={remove}><input type="hidden" name="id" value={item.id}/><button className="danger-link">Excluir</button></form></div></div>)}</div></main>}
