import type { Metadata } from "next";
import Link from "next/link";
import { Header } from "@/components/Header";
import { SiteFooter } from "@/components/SiteFooter";

export const metadata: Metadata = { title: "Termos de Uso", description: "Termos de uso do site ALUNERI.", alternates: { canonical: "/termos", languages: { "pt-BR": "/termos", en: "/en/terms" } } };

export default function TermsPage() {
  return <main id="conteudo"><Header/><section className="inner-page-hero legal-hero"><div className="shell"><Link className="case-back" href="/">← Voltar</Link><div className="inner-page-copy"><span className="eyebrow">Legal</span><h1>Termos de uso</h1><p>Regras simples para o uso público do portfólio, formulários e propostas da ALUNERI.</p><span className="legal-updated">Última atualização: 14 de setembro de 2026</span></div></div></section><section className="section legal-section"><div className="shell legal-content"><div className="legal-grid"><article><h2>Conteúdo do site</h2><p>O conteúdo apresenta serviços, cases, capacidades e informações institucionais. Materiais podem ser atualizados conforme o portfólio evolui.</p></article><article><h2>Briefings</h2><p>O envio de um briefing inicia uma conversa e não cria obrigação de contratação, reserva de agenda ou compromisso financeiro.</p></article><article><h2>Orçamentos e propostas</h2><p>Escopo, investimento, prazo, validade e demais condições somente se tornam aplicáveis quando formalizados e aceitos pelas partes.</p></article><article><h2>Cases e materiais</h2><p>Screenshots, interfaces, marcas e descrições de projetos são apresentados em contexto de portfólio. Dados sensíveis devem permanecer protegidos.</p></article><article><h2>Assistente de IA</h2><p>Respostas do Assistente ALUNERI são informativas e podem conter erros. Preços, prazos, escopo, disponibilidade e condições comerciais só valem quando confirmados por uma pessoa e formalizados em proposta.</p></article><article><h2>Links externos</h2><p>WhatsApp, GitHub, demos e outros destinos externos possuem regras e políticas próprias.</p></article><article><h2>Disponibilidade</h2><p>A ALUNERI trabalha para manter o site seguro e disponível, mas serviços de internet podem apresentar indisponibilidades, manutenção ou falhas fora do controle direto.</p></article><article><h2>Privacidade</h2><p>O tratamento de dados e preferências é explicado nas páginas de <Link href="/privacidade">Privacidade</Link> e <Link href="/cookies">Cookies</Link>.</p></article><article><h2>Uso adequado</h2><p>Não utilize formulários ou endpoints para abuso, spam, tentativa de exploração, automação maliciosa ou envio de conteúdo ilegal.</p></article></div></div></section><SiteFooter/></main>;
}
