import Link from "next/link";
import { notFound } from "next/navigation";
import { revalidatePath } from "next/cache";
import { getRow, updateRow } from "@/lib/server/supabase";
import type { Proposal } from "@/lib/server/business";
import { siteUrl } from "@/lib/site";

export default async function ProposalDetail({params}:{params:Promise<{id:string}>}){ const {id}=await params; const p=await getRow<Proposal>('proposals',id); if(!p)notFound();
async function update(formData:FormData){'use server'; await updateRow('proposals',id,{status:String(formData.get('status')||'draft'),terms:String(formData.get('terms')||'').slice(0,8000),updated_at:new Date().toISOString()}); revalidatePath(`/admin/propostas/${id}`);}
const publicUrl=`${siteUrl}/proposta/${p.token}`; return <main className="admin-page"><Link className="admin-back" href="/admin/propostas">← Propostas</Link><div className="admin-page-heading"><div><span>Proposta</span><h1>{p.title}</h1></div><span className={`admin-status status-${p.status}`}>{p.status}</span></div><div className="admin-two-column"><section className="admin-panel"><h2>Resumo</h2><dl className="admin-details"><dt>Cliente</dt><dd>{p.client_name}</dd><dt>Empresa</dt><dd>{p.company||'-'}</dd><dt>Valor</dt><dd>{p.price_cents?new Intl.NumberFormat('pt-BR',{style:'currency',currency:p.currency}).format(p.price_cents/100):'-'}</dd><dt>Prazo</dt><dd>{p.deadline||'-'}</dd><dt>Validade</dt><dd>{p.valid_until||'-'}</dd><dt>Link público</dt><dd><a href={publicUrl} target="_blank" rel="noreferrer">{publicUrl}</a></dd></dl></section><section className="admin-panel"><h2>Status e termos</h2><form className="admin-form" action={update}><label>Status<select name="status" defaultValue={p.status}>{['draft','sent','accepted','rejected','expired'].map(s=><option key={s}>{s}</option>)}</select></label><label>Termos<textarea name="terms" defaultValue={p.terms||''} rows={10}/></label><button className="button button-primary">Salvar</button></form></section></div><section className="admin-panel"><h2>Escopo</h2><p className="admin-pre">{p.scope}</p><h3>Entregáveis</h3><ul>{p.deliverables.map(d=><li key={d}>{d}</li>)}</ul></section></main> }
