"use client";

import { type ChangeEvent, type FormEvent, useEffect, useMemo, useState } from "react";
import { ArrowLeft, ArrowRight, ArrowUpRight, Check, Code, WhatsApp } from "@/components/Icons";
import { contact } from "@/data/portfolio";

const projectTypes=["Site institucional","Dashboard","Sistema web","SaaS & produtos digitais","Sistema administrativo","Automação / integração","Outro"];
const featureOptions=["Login / contas","Painel administrativo","Banco de dados","Pagamentos","Integração com APIs","Relatórios / dashboards","WhatsApp / notificações","Responsividade mobile"];
const budgetOptions=["Ainda não defini","Até R$ 2.500","R$ 2.500 a R$ 5.000","R$ 5.000 a R$ 10.000","Acima de R$ 10.000"];
const timelineOptions=["Sem urgência","Até 30 dias","1 a 2 meses","2 a 4 meses","Quero conversar primeiro"];

type FormState={name:string;company:string;email:string;phone:string;type:string;features:string[];budget:string;timeline:string;details:string;privacyAccepted:boolean;website:string};
const steps=[{number:"01",title:"Projeto",description:"O que você quer construir?"},{number:"02",title:"Recursos",description:"O que precisa fazer parte?"},{number:"03",title:"Contexto",description:"Prazo, investimento e problema."},{number:"04",title:"Revisão",description:"Confira antes de enviar."}];

export function ContactBriefForm(){
  const [step,setStep]=useState(0);const [copied,setCopied]=useState(false);const [submitting,setSubmitting]=useState(false);const [submitState,setSubmitState]=useState<"idle"|"saved"|"error">("idle");
  const [form,setForm]=useState<FormState>({name:"",company:"",email:"",phone:"",type:projectTypes[0],features:[],budget:budgetOptions[0],timeline:timelineOptions[0],details:"",privacyAccepted:false,website:""});
  useEffect(()=>{const requestedType=new URLSearchParams(window.location.search).get("tipo");if(!requestedType)return;const normalized=requestedType.toLocaleLowerCase("pt-BR");const direct=projectTypes.find(o=>o.toLocaleLowerCase("pt-BR")===normalized);const inferred=direct||(normalized.includes("dashboard")?"Dashboard":null)||(normalized.includes("site")?"Site institucional":null)||(normalized.includes("saas")?"SaaS & produtos digitais":null)||(normalized.includes("administr")?"Sistema administrativo":null)||((normalized.includes("autom")||normalized.includes("integra"))?"Automação / integração":null)||((normalized.includes("painel")||normalized.includes("sistema"))?"Sistema web":null);if(inferred)setForm(c=>({...c,type:inferred}))},[]);
  const brief=useMemo(()=>{const company=form.company.trim()?`\nEmpresa/projeto: ${form.company.trim()}`:"";const contactLine=`\nContato: ${form.email.trim()||form.phone.trim()||"Não informado"}`;const features=form.features.length?form.features.map(f=>`- ${f}`).join("\n"):"- Quero definir os recursos durante a conversa";return `Olá! Vi o portfólio da ALUNERI e gostaria de solicitar um orçamento.\n\nNome: ${form.name.trim()||"Não informado"}${company}${contactLine}\nTipo de projeto: ${form.type}\n\nRecursos importantes:\n${features}\n\nFaixa de investimento: ${form.budget}\nPrazo: ${form.timeline}\n\nContexto do projeto:\n${form.details.trim()||"Quero explicar melhor durante a conversa."}`},[form]);
  const whatsappUrl=`${contact.whatsappBase}?text=${encodeURIComponent(brief)}`;const update=<K extends keyof FormState,>(field:K,value:FormState[K])=>setForm(c=>({...c,[field]:value}));const toggleFeature=(feature:string)=>setForm(c=>({...c,features:c.features.includes(feature)?c.features.filter(i=>i!==feature):[...c.features,feature]}));
  const canContinue=step!==0||(form.name.trim().length>1&&Boolean(form.email.trim()||form.phone.trim())&&form.type.trim().length>0);
  const submit=async(event:FormEvent)=>{event.preventDefault();if(step<steps.length-1){if(canContinue)setStep(c=>Math.min(c+1,steps.length-1));return}if(!form.privacyAccepted){setSubmitState("error");return}setSubmitting(true);setSubmitState("idle");const popup=window.open("about:blank","_blank");try{const response=await fetch("/api/leads",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name:form.name,company:form.company,email:form.email,phone:form.phone,projectType:form.type,features:form.features,budget:form.budget,timeline:form.timeline,details:form.details,privacyAccepted:form.privacyAccepted,website:form.website,source:window.location.pathname})});if(!response.ok)throw new Error();setSubmitState("saved");if(popup)popup.location.href=whatsappUrl;else window.open(whatsappUrl,"_blank","noopener,noreferrer")}catch{if(popup)popup.close();setSubmitState("error")}finally{setSubmitting(false)}};
  const copyBrief=async()=>{await navigator.clipboard.writeText(brief);setCopied(true);window.setTimeout(()=>setCopied(false),1800)};
  return <form className="brief-form brief-wizard" onSubmit={submit}><input className="form-honeypot" tabIndex={-1} autoComplete="off" aria-hidden="true" name="website" value={form.website} onChange={e=>update("website",e.target.value)}/><div className="brief-wizard-progress"><div className="brief-wizard-progress-top"><span>Briefing em etapas</span><strong>{step+1}/{steps.length}</strong></div><div className="brief-wizard-track"><span style={{width:`${((step+1)/steps.length)*100}%`}}/></div><div className="brief-wizard-step-labels">{steps.map((item,index)=><button type="button" key={item.number} className={index===step?"active":index<step?"done":""} onClick={()=>{if(index<=step||canContinue)setStep(index)}} aria-current={index===step?"step":undefined}><span>{index<step?<Check size={13}/>:item.number}</span><div><strong>{item.title}</strong><small>{item.description}</small></div></button>)}</div></div>
  <div className="brief-wizard-panel" aria-live="polite">{step===0&&<div className="brief-step-content"><div className="brief-step-heading"><span className="eyebrow">Etapa 01</span><h3>Vamos começar pelo básico.</h3><p>Nome, contato e o formato mais próximo do que você imagina hoje.</p></div><div className="brief-form-grid"><label><span>Seu nome</span><input required maxLength={80} autoComplete="name" value={form.name} onChange={(e:ChangeEvent<HTMLInputElement>)=>update("name",e.target.value)} placeholder="Como podemos te chamar?"/></label><label><span>Empresa ou projeto <small>opcional</small></span><input maxLength={100} autoComplete="organization" value={form.company} onChange={(e:ChangeEvent<HTMLInputElement>)=>update("company",e.target.value)} placeholder="Nome da empresa ou ideia"/></label><label><span>Email</span><input type="email" maxLength={180} autoComplete="email" value={form.email} onChange={e=>update("email",e.target.value)} placeholder="voce@empresa.com"/></label><label><span>WhatsApp</span><input maxLength={40} autoComplete="tel" value={form.phone} onChange={e=>update("phone",e.target.value)} placeholder="+55 ..."/></label><label className="brief-details"><span>Tipo de projeto</span><select value={form.type} onChange={e=>update("type",e.target.value)}>{projectTypes.map(o=><option key={o}>{o}</option>)}</select></label></div><p className="brief-contact-hint">Informe pelo menos email ou WhatsApp para o CRM conseguir retornar seu contato.</p></div>}
  {step===1&&<div className="brief-step-content"><div className="brief-step-heading"><span className="eyebrow">Etapa 02</span><h3>Quais recursos parecem importantes?</h3><p>Não precisa ter certeza. Marque apenas o que já faz sentido para a ideia.</p></div><div className="brief-feature-grid">{featureOptions.map(feature=>{const active=form.features.includes(feature);return <button type="button" key={feature} className={active?"active":""} onClick={()=>toggleFeature(feature)} aria-pressed={active}><span>{active?<Check size={15}/>:"+"}</span>{feature}</button>})}</div></div>}
  {step===2&&<div className="brief-step-content"><div className="brief-step-heading"><span className="eyebrow">Etapa 03</span><h3>Agora o contexto.</h3><p>Prazo, investimento e o problema que o produto precisa resolver.</p></div><div className="brief-form-grid"><label><span>Faixa de investimento</span><select value={form.budget} onChange={e=>update("budget",e.target.value)}>{budgetOptions.map(o=><option key={o}>{o}</option>)}</select></label><label><span>Prazo desejado</span><select value={form.timeline} onChange={e=>update("timeline",e.target.value)}>{timelineOptions.map(o=><option key={o}>{o}</option>)}</select></label><label className="brief-details"><span>Conte um pouco sobre o projeto</span><textarea maxLength={3000} value={form.details} onChange={e=>update("details",e.target.value)} placeholder="Problema que quer resolver, usuários, páginas, referências, integrações e qualquer detalhe importante..." rows={8}/><small>{form.details.length}/3000 caracteres</small></label></div></div>}
  {step===3&&<div className="brief-step-content"><div className="brief-step-heading"><span className="eyebrow">Etapa 04</span><h3>Revise antes de enviar.</h3><p>Ao enviar, o briefing é registrado no CRM da ALUNERI quando o backend estiver configurado e a conversa no WhatsApp é aberta com a mesma mensagem.</p></div><div className="brief-preview wizard-preview"><div><span className="brief-preview-icon"><Code/></span><div><strong>Mensagem pronta para WhatsApp</strong><p>O mesmo contexto fica associado ao lead no painel.</p></div></div><pre>{brief}</pre></div><label className="brief-privacy-check"><input type="checkbox" checked={form.privacyAccepted} onChange={e=>update("privacyAccepted",e.target.checked)}/><span>Concordo com o uso desses dados para responder ao meu pedido, conforme a <a href="/privacidade" target="_blank">Política de Privacidade</a>.</span></label>{submitState==="saved"&&<div className="form-success"><Check/> Briefing registrado. Abrindo WhatsApp…</div>}{submitState==="error"&&<div className="form-error">Não foi possível registrar ou falta aceitar a política de privacidade. Tente novamente.</div>}</div>}</div>
  <div className="brief-wizard-actions"><button type="button" className="button button-secondary" onClick={()=>setStep(c=>Math.max(0,c-1))} disabled={step===0}><ArrowLeft/> Voltar</button><div>{step===steps.length-1&&<button type="button" className="button button-secondary" onClick={copyBrief}>{copied?<Check/>:<Code/>}{copied?"Briefing copiado":"Copiar"}</button>}<button type="submit" className={step===steps.length-1?"button button-whatsapp":"button button-primary"} disabled={!canContinue||submitting}>{step===steps.length-1?<><WhatsApp/> {submitting?"Registrando...":"Registrar e abrir WhatsApp"} <ArrowUpRight size={16}/></>:<>Continuar <ArrowRight/></>}</button></div></div></form>
}
