"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { usePathname } from "next/navigation";
import { Close, Menu } from "@/components/Icons";
import { NexoraLogo } from "@/components/NexoraLogo";
import { brand } from "@/data/portfolio";

const ptLinks=[["/#inicio","Início"],["/projetos","Projetos"],["/#processo","Processo"],["/servicos","Serviços"],["/sobre","Sobre"],["/contato","Contato"]];
const enLinks=[["/en#home","Home"],["/en/projects","Projects"],["/en#process","Process"],["/en/services","Services"],["/en/about","About"],["/en/contact","Contact"]];

function languageTarget(pathname:string,isEn:boolean){const ptToEn:Record<string,string>={"/":"/en","/servicos":"/en/services","/contato":"/en/contact","/sobre":"/en/about","/projetos":"/en/projects","/resultados":"/en/results","/agendar":"/en/schedule","/projetos/zentra":"/en/projects/zentra","/projetos/spazio-gestao":"/en/projects/spazio-management"};const enToPt:Record<string,string>={"/en":"/","/en/services":"/servicos","/en/contact":"/contato","/en/about":"/sobre","/en/projects":"/projetos","/en/results":"/resultados","/en/schedule":"/agendar","/en/projects/zentra":"/projetos/zentra","/en/projects/spazio-management":"/projetos/spazio-gestao"};if(isEn){if(enToPt[pathname])return enToPt[pathname];if(pathname.startsWith("/en/projects/"))return pathname.replace("/en/projects/","/projetos/");return "/"}if(ptToEn[pathname])return ptToEn[pathname];if(pathname.startsWith("/projetos/"))return pathname.replace("/projetos/","/en/projects/");return "/en"}

export function Header(){const [open,setOpen]=useState(false);const pathname=usePathname();const isEn=pathname.startsWith('/en');const links=isEn?enLinks:ptLinks;useEffect(()=>{if(!open)return;const onKeyDown=(event:KeyboardEvent)=>{if(event.key==='Escape')setOpen(false)};window.addEventListener('keydown',onKeyDown);return()=>window.removeEventListener('keydown',onKeyDown)},[open]);return <header className="site-header"><div className="shell header-inner"><Link className="brand" href={isEn?'/en#home':'/#inicio'} aria-label="NEXORA"><NexoraLogo className="brand-logo"/></Link><nav className="desktop-nav" aria-label={isEn?'Main navigation':'Navegação principal'}>{links.map(([href,label])=><Link key={href} href={href}>{label}</Link>)}<Link className="language-switch" href={languageTarget(pathname,isEn)}>{isEn?'PT':'EN'}</Link></nav><Link className="availability-pill desktop-availability" href={isEn?'/en/contact':'/contato'}><span className="pulse-dot" aria-hidden="true"/>{isEn?'Available for new projects':brand.availability}</Link><button type="button" className="menu-button" onClick={()=>setOpen(v=>!v)} aria-label={open?(isEn?'Close menu':'Fechar menu'):(isEn?'Open menu':'Abrir menu')} aria-expanded={open} aria-controls="menu-mobile">{open?<Close/>:<Menu/>}</button></div>{open&&<div className="mobile-menu" id="menu-mobile"><nav className="shell mobile-menu-inner" aria-label={isEn?'Mobile navigation':'Navegação mobile'}>{links.map(([href,label])=><Link key={href} href={href} onClick={()=>setOpen(false)}>{label}</Link>)}<Link href={languageTarget(pathname,isEn)} onClick={()=>setOpen(false)}>{isEn?'Português':'English'}</Link><Link href={isEn?'/en/contact':'/contato'} className="availability-pill" onClick={()=>setOpen(false)}><span className="pulse-dot" aria-hidden="true"/>{isEn?'Available for new projects':brand.availability}</Link></nav></div>}</header>}
