"use client";
import { FormEvent, useMemo, useState } from "react";
import { ArrowUpRight, Check, WhatsApp } from "@/components/Icons";
import { contact } from "@/data/portfolio";

const periods=["Manhã (09h–12h)","Tarde (14h–18h)","Noite (19h–21h)"];
export function ScheduleForm(){const [state,setState]=useState({name:"",email:"",phone:"",date:"",period:periods[1],notes:"",privacy:false,website:""});const [status,setStatus]=useState<"idle"|"sending"|"ok"|"error">("idle");const minDate=useMemo(()=>new Date(Date.now()+86400000).toISOString().slice(0,10),[]);const message=`Olá! Gostaria de solicitar uma conversa com a ALUNERI.\n\nNome: ${state.name}\nData preferida: ${state.date}\nPeríodo: ${state.period}\nContato: ${state.email||state.phone}\nObservações: ${state.notes||'-'}`;const whatsapp=`${contact.whatsappBase}?text=${encodeURIComponent(message)}`;
async function submit(e:FormEvent){e.preventDefault();setStatus('sending');try{const res=await fetch('/api/appointments',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:state.name,email:state.email,phone:state.phone,preferredDate:state.date,preferredPeriod:state.period,timezone:Intl.DateTimeFormat().resolvedOptions().timeZone,notes:state.notes,privacyAccepted:state.privacy,website:state.website})});if(!res.ok)throw new Error();setStatus('ok')}catch{setStatus('error')}}
return <form className="schedule-form" onSubmit={submit}><label>Nome<input required maxLength={80} value={state.name} onChange={e=>setState({...state,name:e.target.value})}/></label><div className="schedule-grid"><label>Email<input type="email" maxLength={180} value={state.email} onChange={e=>setState({...state,email:e.target.value})}/></label><label>WhatsApp<input maxLength={40} value={state.phone} onChange={e=>setState({...state,phone:e.target.value})}/></label></div><div className="schedule-grid"><label>Data preferida<input required type="date" min={minDate} value={state.date} onChange={e=>setState({...state,date:e.target.value})}/></label><label>Período<select value={state.period} onChange={e=>setState({...state,period:e.target.value})}>{periods.map(p=><option key={p}>{p}</option>)}</select></label></div><label>Observações<textarea maxLength={1000} rows={5} value={state.notes} onChange={e=>setState({...state,notes:e.target.value})} placeholder="Assunto da conversa, disponibilidade alternativa..."/></label><label className="brief-privacy-check"><input type="checkbox" checked={state.privacy} onChange={e=>setState({...state,privacy:e.target.checked})}/><span>Concordo com o uso desses dados para responder ao pedido de reunião, conforme a <a href="/privacidade" target="_blank">Política de Privacidade</a>.</span></label><input className="form-honeypot" tabIndex={-1} autoComplete="off" name="website" value={state.website} onChange={e=>setState({...state,website:e.target.value})}/><p className="schedule-note">Isto é uma solicitação de horário, não uma confirmação automática. A ALUNERI confirma o encontro depois do contato.</p>{status==='ok'?<div className="schedule-success"><Check/> Solicitação registrada. <a href={whatsapp} target="_blank" rel="noreferrer">Continuar no WhatsApp <ArrowUpRight size={14}/></a></div>:<button className="button button-primary" disabled={status==='sending'||(!state.email&&!state.phone)||!state.privacy}>{status==='sending'?'Enviando...':'Solicitar horário'}</button>}{status==='error'&&<p className="form-error">Não foi possível registrar. Você ainda pode <a href={whatsapp} target="_blank" rel="noreferrer"><WhatsApp size={14}/> falar pelo WhatsApp</a>.</p>}</form>}
