import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { Header } from "@/components/Header";
import { ArrowLeft, ArrowRight } from "@/components/Icons";
import { getCmsProjectBySlug } from "@/lib/server/business";
import { safeHttpsUrl } from "@/lib/security";

export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params;const p=await getCmsProjectBySlug(slug);if(!p)return{};return{title:p.title,description:p.description,alternates:{canonical:`/projetos/${p.slug}`}}}
export default async function CmsPublicProject({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const project=await getCmsProjectBySlug(slug);if(!project)notFound();const image=safeHttpsUrl(project.image_url);const demo=safeHttpsUrl(project.demo_url);return <main id="conteudo"><Header/><section className="case-hero"><div className="shell"><Link className="case-back" href="/projetos"><ArrowLeft/> Voltar aos projetos</Link><div className="case-hero-grid"><div><span className="eyebrow">{project.eyebrow||project.category||'Projeto ALUNERI'}</span><h1>{project.title}</h1><p>{project.description}</p><div className="case-tags">{project.tags.map(t=><span key={t}>{t}</span>)}</div>{demo&&<div className="case-hero-actions"><a className="button button-primary" href={demo} target="_blank" rel="noreferrer">Abrir demo <ArrowRight/></a></div>}</div>{image&&<div className="cms-case-cover"><img src={image} alt={project.title} referrerPolicy="no-referrer"/></div>}</div></div></section><section className="case-section"><div className="shell case-story-grid"><div className="case-story-title"><span className="eyebrow">Sobre o projeto</span><h2>Contexto e<br/>entrega.</h2></div><div className="case-story-content"><div className="story-block"><span>01</span><div><h3>O produto</h3><p>{project.long_description||project.description}</p></div></div>{project.metrics?.length>0&&<div className="story-block"><span>02</span><div><h3>Resultados confirmados</h3><div className="cms-metrics">{project.metrics.map((m,index)=><div key={`${m.label}-${index}`}><strong>{m.value}</strong><span>{m.label}</span><p>{m.description||''}</p></div>)}</div></div></div>}</div></div></section></main>}
