import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { PrintProposalButton } from "@/components/PrintProposalButton";
import { AluneriLogo } from "@/components/AluneriLogo";
import { getProposalByToken } from "@/lib/server/business";
import { contact } from "@/data/portfolio";

export const metadata: Metadata={title:"Proposta comercial",robots:{index:false,follow:false}};
export default async function PublicProposal({params}:{params:Promise<{token:string}>}){const {token}=await params;const proposal=await getProposalByToken(token);if(!proposal)notFound();const money=proposal.price_cents?new Intl.NumberFormat('pt-BR',{style:'currency',currency:proposal.currency}).format(proposal.price_cents/100):'A definir';const whatsapp=`${contact.whatsappBase}?text=${encodeURIComponent(`Olá! Recebi a proposta "${proposal.title}" e gostaria de conversar sobre ela.`)}`;
return <main className="proposal-page"><header className="proposal-header"><AluneriLogo className="proposal-logo"/><span>Proposta comercial</span></header><section className="proposal-hero"><span>Preparada para</span><h1>{proposal.client_name}</h1>{proposal.company&&<p>{proposal.company}</p>}<div className="proposal-meta"><div><small>Projeto</small><strong>{proposal.title}</strong></div><div><small>Investimento</small><strong>{money}</strong></div><div><small>Prazo</small><strong>{proposal.deadline||'A definir'}</strong></div><div><small>Validade</small><strong>{proposal.valid_until||'A combinar'}</strong></div></div></section><section className="proposal-section"><span>01</span><div><h2>Escopo</h2><p>{proposal.scope}</p></div></section><section className="proposal-section"><span>02</span><div><h2>Entregáveis</h2><ul>{proposal.deliverables.map(item=><li key={item}>{item}</li>)}</ul></div></section>{proposal.terms&&<section className="proposal-section"><span>03</span><div><h2>Condições</h2><p>{proposal.terms}</p></div></section>}<section className="proposal-actions no-print"><a className="button button-whatsapp" href={whatsapp} target="_blank" rel="noreferrer">Conversar sobre a proposta</a><PrintProposalButton/><Link className="button button-secondary" href="/">ALUNERI</Link></section><footer className="proposal-footer"><strong>ALUNERI</strong><span>Produtos Digitais & Sistemas</span><small>Status da proposta: {proposal.status}</small></footer></main>}
